### PR TITLE
CPG-generator/query-language integration testing setup

### PR DESCRIPTION
**Pull request by fabsx00**
This PR introduces a sub project named `testing` that tests integration between the plume CPG generator and the query language formulated in `codepropertygraph`. In detail, the following changes were required to make this work:

* The main application needed to be moved to its own sub project to allow the scala-based tests to access the extractor
* For the new sub project `testing`, the `scalatest` plugin was included so that `gradle test` executes the tests correctly
* A `PlumeCodeToCpgSuite` testing suite was introduced that allows tests to be written based on Java source code
* `gradle scalafmt` and `gradle test:scalafmt` were run once, causing light layout adaptions in `CpgDomainObjectCreator`
* Added commented-out tests that show some remaining problems with the `Method` representation
* Allow running scala tests with `gradlew scalatest`
* Run scalatests via `gradlew allTests` and in CI

### CODE REVIEW

**Comment by fabsx00** [comment]
Update: I'm not sure all tests are run with this setup. Let me dig into that and get back to you.

**Comment by fabsx00** [comment]
Ok, works.

**Review by DavidBakerEffendi — COMMENTED** [review]
Looks good! I'm just wondering if we shouldn't (a) consider renaming `extractor` to `plume` since the driver classes will be reuse in the analysis (which will be more than extracting.) or (b) split extractor and driver logic into 2 Gradle subprojects again.

I can jump in to do (b) but perhaps (a) will be the simplest.

**Comment by fabsx00** [comment]
Sub projects in a single repo sound good. That gives us the best of both worlds. On the one hand, compatible extractor and driver code have a single commit hash, on the other hand, the code is nicely structured into components with explicitly defined dependencies.

**Review by DavidBakerEffendi — APPROVED** [review]
Looks good!

**Pull request merged**
